### ISSUE TITLE
Make an installer of some kind - Possibly a Docker container

### ISSUE THREAD

**Issue by ZNielsen** [ZNielsen/PodRacer#51]
- Set up directory and symlinks 
- Setup wizard?

**Comment by ZNielsen** [comment]
Probably would be good to make this a Docker image.

**Comment by ZNielsen** [comment]
https://hackernoon.com/how-to-dockerize-any-application-b60ad00e76da

**Comment by Macleykun** [comment]
Heya, i would like to help you out on this but it seems that during the compile on x84_64, the compiler panicked.
```
root@490566ed9f5e:/PodRacer# rustup override set nightly && rustup update && cargo update && cargo build --release
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: override toolchain for '/PodRacer' set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.68.0-nightly (9c07efe84 2022-12-16)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.68.0-nightly (9c07efe84 2022-12-16)

info: cleaning up downloads & tmp directories
    Updating crates.io index
warning: for loop over an `Option`. This is more readably written as an `if let` statement
    --> racer/src/lib.rs:1339:30
     |
1339 |                 for links in atom.get_mut("link") {
     |                              ^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(for_loops_over_fallibles)]` on by default
help: to check pattern in a loop use `while let`
     |
1339 |                 while let Some(links) = atom.get_mut("link") {
     |                 ~~~~~~~~~~~~~~~     ~~~
help: consider using `if let` to clear intent
     |
1339 |                 if let Some(links) = atom.get_mut("link") {
     |                 ~~~~~~~~~~~~     ~~~

warning: `racer` (lib) generated 1 warning
   Compiling podracer v0.2.1 (/PodRacer/server)
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:969:13: failed to get layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>`: unable to determine layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` cannot be normalized

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0:     0x7feaba028d5a - std::backtrace_rs::backtrace::libunwind::trace::hf3e23dba944728e7
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7feaba028d5a - std::backtrace_rs::backtrace::trace_unsynchronized::ha7a661dbe14f9bec
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7feaba028d5a - std::sys_common::backtrace::_print_fmt::h8bb3e793399a1d31
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7feaba028d5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f001b4156af7ff0
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7feab5fb536e - core::fmt::write::h98c67bacb0ad9cb8
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/core/src/fmt/mod.rs:1208:17
   5:     0x7feaba01ce35 - std::io::Write::write_fmt::h21d43ee83b8bf3da
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/io/mod.rs:1682:15
   6:     0x7feaba028b25 - std::sys_common::backtrace::_print::hed3e659c4722fff2
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7feaba028b25 - std::sys_common::backtrace::print::hf3af686623d05885
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7feaba02aeaf - std::panicking::default_hook::{{closure}}::hfbc532e2813a4fd8
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/panicking.rs:267:22
   9:     0x7feaba02abeb - std::panicking::default_hook::hf22d9a6bedeb8cbb
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/panicking.rs:286:9
  10:     0x7feab9254351 - rustc_driver[8203396c4671b89c]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7feaba02b6ad - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h839d8563a5defb2f
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/alloc/src/boxed.rs:2032:9
  12:     0x7feaba02b6ad - std::panicking::rust_panic_with_hook::h2e7c62506c5adf89
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/panicking.rs:692:13
  13:     0x7feab90ece41 - std[fecc2c98d64c5e20]::panicking::begin_panic::<rustc_errors[6c86e693eff69e36]::ExplicitBug>::{closure#0}
  14:     0x7feab90ec616 - std[fecc2c98d64c5e20]::sys_common::backtrace::__rust_end_short_backtrace::<std[fecc2c98d64c5e20]::panicking::begin_panic<rustc_errors[6c86e693eff69e36]::ExplicitBug>::{closure#0}, !>
  15:     0x7feab9086846 - std[fecc2c98d64c5e20]::panicking::begin_panic::<rustc_errors[6c86e693eff69e36]::ExplicitBug>
  16:     0x7feab90ec436 - std[fecc2c98d64c5e20]::panic::panic_any::<rustc_errors[6c86e693eff69e36]::ExplicitBug>
  17:     0x7feab90e9689 - <rustc_errors[6c86e693eff69e36]::HandlerInner>::span_bug::<rustc_span[b683b297262634fe]::span_encoding::Span, &alloc[4e38580f0181725e]::string::String>
  18:     0x7feab90e92f0 - <rustc_errors[6c86e693eff69e36]::Handler>::span_bug::<rustc_span[b683b297262634fe]::span_encoding::Span, &alloc[4e38580f0181725e]::string::String>
  19:     0x7feab90ec7b9 - rustc_middle[46166420d424f8d9]::ty::context::tls::with_context_opt::<rustc_middle[46166420d424f8d9]::ty::context::tls::with_opt<rustc_middle[46166420d424f8d9]::util::bug::opt_span_bug_fmt<rustc_span[b683b297262634fe]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7feab90ec546 - rustc_middle[46166420d424f8d9]::util::bug::opt_span_bug_fmt::<rustc_span[b683b297262634fe]::span_encoding::Span>
  21:     0x7feab79516c4 - rustc_middle[46166420d424f8d9]::util::bug::span_bug_fmt::<rustc_span[b683b297262634fe]::span_encoding::Span>
  22:     0x7feab90902f2 - <rustc_codegen_llvm[30227101449b2fe9]::context::CodegenCx as rustc_middle[46166420d424f8d9]::ty::layout::LayoutOfHelpers>::handle_layout_err
  23:     0x7feab908ce51 - <rustc_codegen_llvm[30227101449b2fe9]::context::CodegenCx as rustc_middle[46166420d424f8d9]::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
  24:     0x7feab908fd4a - <rustc_codegen_llvm[30227101449b2fe9]::context::CodegenCx as rustc_middle[46166420d424f8d9]::ty::layout::LayoutOf>::layout_of
  25:     0x7feab9085356 - <rustc_codegen_ssa[b132c7f3e732167f]::mir::place::PlaceRef<&rustc_codegen_llvm[30227101449b2fe9]::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>
  26:     0x7feab79552f9 - <rustc_codegen_ssa[b132c7f3e732167f]::mir::FunctionCx<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>>::codegen_place
  27:     0x7feab7931130 - <rustc_codegen_ssa[b132c7f3e732167f]::mir::FunctionCx<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>>::codegen_block
  28:     0x7feab791e0d7 - rustc_codegen_ssa[b132c7f3e732167f]::mir::codegen_mir::<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>
  29:     0x7feab8710af6 - rustc_codegen_llvm[30227101449b2fe9]::base::compile_codegen_unit::module_codegen
  30:     0x7feab88e4423 - <rustc_query_system[b2d3787a6eb3f954]::dep_graph::graph::DepGraph<rustc_middle[46166420d424f8d9]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[46166420d424f8d9]::ty::context::TyCtxt, rustc_span[b683b297262634fe]::symbol::Symbol, rustc_codegen_ssa[b132c7f3e732167f]::ModuleCodegen<rustc_codegen_llvm[30227101449b2fe9]::ModuleLlvm>>
  31:     0x7feab88e413e - <rustc_codegen_llvm[30227101449b2fe9]::LlvmCodegenBackend as rustc_codegen_ssa[b132c7f3e732167f]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  32:     0x7feab88e1a22 - rustc_codegen_ssa[b132c7f3e732167f]::base::codegen_crate::<rustc_codegen_llvm[30227101449b2fe9]::LlvmCodegenBackend>
  33:     0x7feab88e11c9 - <rustc_codegen_llvm[30227101449b2fe9]::LlvmCodegenBackend as rustc_codegen_ssa[b132c7f3e732167f]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7feab84dd8b1 - <rustc_session[23982924e285e106]::session::Session>::time::<alloc[4e38580f0181725e]::boxed::Box<dyn core[4c48bf2e04a135c7]::any::Any>, rustc_interface[3feed755d27e3616]::passes::start_codegen::{closure#0}>
  35:     0x7feab84dd3d9 - rustc_interface[3feed755d27e3616]::passes::start_codegen
  36:     0x7feab84db0d6 - <rustc_interface[3feed755d27e3616]::passes::QueryContext>::enter::<<rustc_interface[3feed755d27e3616]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[4c48bf2e04a135c7]::result::Result<alloc[4e38580f0181725e]::boxed::Box<dyn core[4c48bf2e04a135c7]::any::Any>, rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  37:     0x7feab84d8586 - <rustc_interface[3feed755d27e3616]::queries::Queries>::ongoing_codegen
  38:     0x7feab84d7aa7 - <rustc_interface[3feed755d27e3616]::interface::Compiler>::enter::<rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}::{closure#2}, core[4c48bf2e04a135c7]::result::Result<core[4c48bf2e04a135c7]::option::Option<rustc_interface[3feed755d27e3616]::queries::Linker>, rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  39:     0x7feab84d2a88 - rustc_span[b683b297262634fe]::with_source_map::<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  40:     0x7feab84d2575 - <scoped_tls[b4ee55afb72dd1f]::ScopedKey<rustc_span[b683b297262634fe]::SessionGlobals>>::set::<rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  41:     0x7feab84d1b62 - std[fecc2c98d64c5e20]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3feed755d27e3616]::util::run_in_thread_pool_with_globals<rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  42:     0x7feab8b121fe - <<std[fecc2c98d64c5e20]::thread::Builder>::spawn_unchecked_<rustc_interface[3feed755d27e3616]::util::run_in_thread_pool_with_globals<rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>::{closure#1} as core[4c48bf2e04a135c7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7feaba032923 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha40757527af5f65d
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/alloc/src/boxed.rs:2000:9
  44:     0x7feaba032923 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf5bd55cd4ab92745
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/alloc/src/boxed.rs:2000:9
  45:     0x7feaba032923 - std::sys::unix::thread::Thread::new::thread_start::h087de3b4a94ba02b
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7feab5e25ea7 - start_thread
  47:     0x7feab5d43a2f - clone
  48:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (9c07efe84 2022-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `podracer`
```

Command's i did in the container:
```
    3  apt update
    4  apt install git -y
    6  git clone https://github.com/ZNielsen/PodRacer.git
    7  cd PodRacer
   11  apt install pkg-config libssl-dev -y
   12  rustup override set nightly && rustup update && cargo update && cargo build --release
```
I ran the container with this:
```
docker run -it --rm --name rust-test rust:slim
```
Given the build instructions, i expect the Dockerfile won't be to complex to setup. Once we have a working dockerfile we can later add the CI/CD so you can host the docker images on dockerhub or github registery if you prefer.

Users then only need to use one command to run the container with the image from dockerhub.

**Comment by ZNielsen** [comment]
Looks like a newer nightly might be complaining about a bad practice. I'll take a look and see if I can get this building.

**Comment by ZNielsen** [comment]
So I fixed the warning, but I still get an internal compiler error. I think this is a result of being on nightly. I filed a bug report.

**Comment by Macleykun** [comment]
> So I fixed the warning, but I still get an internal compiler error. I think this is a result of being on nightly. I filed a bug report.

sure np :) thanks for looking into it!

**Comment by ZNielsen** [comment]
Looks like rocket no longer requires nightly. I'll get onto stable then hopefully this won't be a problem.

**Comment by Macleykun** [comment]
> Looks like rocket no longer requires nightly. I'll get onto stable then hopefully this won't be a problem.

sure! I assume you're going to: rust 1.66.0?

**Comment by ZNielsen** [comment]
Yes, 1.66
